# Generated by Django 5.2 on 2025-07-18 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="timestemp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
