# Generated by Django 5.2 on 2025-07-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_timestemp_article_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="timestemp",
            new_name="timestamp",
        ),
    ]
