# Generated by Django 5.2 on 2025-07-18 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_rename_timestemp_article_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="publish",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
