# Generated by Django 5.2 on 2025-07-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_alter_article_publish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="publish",
        ),
    ]
