# Generated by Django 5.2 on 2025-07-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_remove_article_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="publish",
            field=models.DateField(blank=True, null=True),
        ),
    ]
