# Generated by Django 5.2 on 2025-07-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0010_article_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
